apiVersion: v1
kind: Service
metadata:
  name: atas-service
  namespace: atas
  labels:
    app: atas-service
spec:
  type: ClusterIP  # Use LoadBalancer for cloud providers, or Ingress
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: atas-service
  sessionAffinity: None  # Set to ClientIP if sticky sessions needed for SSE

---
# For cloud providers, use LoadBalancer or Ingress
# Example for AWS/GCP/Azure:
# apiVersion: v1
# kind: Service
# metadata:
#   name: atas-service-lb
#   namespace: atas
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # AWS
#     cloud.google.com/load-balancer-type: "Internal"  # GCP
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 8080
#     protocol: TCP
#   selector:
#     app: atas-service



